import { env } from 'cloudflare:workers';

export type EventRecord={nickname:string;id:string;time:number;eventType:string;studentId:string;name:string;session:string;details:string;source:string;actor:string;points:number|null;reversible:number;qrAwardId?:string;qrOpen?:number};
export type LeagueRecord={nickname:string;studentId:string;name:string;email:string;points:number};
export type AttendanceRecord={nickname:string;id:string;time:number;studentId:string;name:string;session:string;room:string;source:string;verification:string;voidedAt:number|null;voidedBy:string;voidReason:string};
export type SessionChoice={id:string;title:string;room:string;openedAt:number;closedAt:number|null};
export type CheckedInRecord={studentId:string;name:string;email:string;nickname:string;checkedInAt:number;classesAttended:number;points:number;interactions:number};
export type EnrolmentRecord={nickname:string;studentId:string;name:string;email:string;groups:string;checkedInAt:number|null};
export type CourseRecords={events:EventRecord[];league:LeagueRecord[];attendance:AttendanceRecord[];enrolments:EnrolmentRecord[];checkedIn:CheckedInRecord[];sessions:SessionChoice[]};

export async function loadCourseRecords(courseId:string):Promise<CourseRecords>{
  const db=env.DB;
  const [enrolments,events,league,attendance,checkedIn,sessions]=await Promise.all([
    db.prepare(`SELECT s.student_number AS studentId,s.name,COALESCE(s.email,'') AS email,e.groups,e.checked_in_at AS checkedInAt FROM enrolments e JOIN students s ON s.id=e.student_id WHERE e.course_id=? AND e.active=1 ORDER BY s.name COLLATE NOCASE,s.student_number`).bind(courseId).all<EnrolmentRecord>(),
    loadEventRecords(courseId),
    db.prepare(`SELECT s.student_number AS studentId,s.name,COALESCE(s.email,'') AS email,COALESCE(SUM(pt.points),0) AS points FROM enrolments e JOIN students s ON s.id=e.student_id LEFT JOIN point_transactions pt ON pt.course_id=e.course_id AND pt.student_id=e.student_id WHERE e.course_id=? AND e.active=1 GROUP BY s.id ORDER BY points DESC,s.name`).bind(courseId).all<LeagueRecord>(),
    db.prepare(`SELECT a.id,a.recorded_at AS time,s.student_number AS studentId,s.name,cs.title AS session,COALESCE(cs.room,'') AS room,a.source,a.identity_verification AS verification,a.voided_at AS voidedAt,COALESCE(u.display_name,'') AS voidedBy,COALESCE(a.void_reason,'') AS voidReason FROM attendance a JOIN students s ON s.id=a.student_id JOIN class_sessions cs ON cs.id=a.session_id LEFT JOIN users u ON u.id=a.voided_by WHERE cs.course_id=? ORDER BY a.recorded_at DESC`).bind(courseId).all<AttendanceRecord>(),
    db.prepare(`SELECT s.student_number AS studentId,s.name,COALESCE(s.email,'') AS email,COALESCE(lp.alias,'') AS nickname,e.checked_in_at AS checkedInAt,(SELECT COUNT(*) FROM attendance a JOIN class_sessions cs ON cs.id=a.session_id WHERE cs.course_id=e.course_id AND a.student_id=e.student_id AND a.voided_at IS NULL) AS classesAttended,COALESCE((SELECT SUM(pt.points) FROM point_transactions pt WHERE pt.course_id=e.course_id AND pt.student_id=e.student_id),0) AS points,(SELECT COUNT(*) FROM point_transactions pt WHERE pt.course_id=e.course_id AND pt.student_id=e.student_id AND pt.points>0) AS interactions FROM enrolments e JOIN students s ON s.id=e.student_id LEFT JOIN leaderboard_preferences lp ON lp.course_id=e.course_id AND lp.student_id=e.student_id WHERE e.course_id=? AND e.active=1 AND e.checked_in_at IS NOT NULL ORDER BY e.checked_in_at,s.name`).bind(courseId).all<CheckedInRecord>(),
    db.prepare(`SELECT id,title,COALESCE(room,'') AS room,opened_at AS openedAt,closed_at AS closedAt FROM class_sessions WHERE course_id=? ORDER BY opened_at DESC`).bind(courseId).all<SessionChoice>(),
  ]);
  const aliases=await db.prepare(`SELECT s.student_number AS studentId,COALESCE(lp.alias,'') AS nickname FROM leaderboard_preferences lp JOIN students s ON s.id=lp.student_id WHERE lp.course_id=?`).bind(courseId).all<{studentId:string;nickname:string}>();
  const nicknames=new Map(aliases.results.map(row=>[row.studentId,row.nickname]));
  const withNicknames=<T extends {studentId:string}>(rows:T[])=>rows.map(row=>({...row,nickname:nicknames.get(row.studentId)??''}));
  return {enrolments:withNicknames(enrolments.results),events:withNicknames(events),league:withNicknames(league.results),attendance:withNicknames(attendance.results),checkedIn:checkedIn.results,sessions:sessions.results};
}

async function loadEventRecords(courseId:string):Promise<EventRecord[]>{
  const db=env.DB,queries=[
    db.prepare(`SELECT cs.id||':opened' AS id,cs.opened_at AS time,'Session opened' AS eventType,'' AS studentId,'' AS name,cs.title AS session,COALESCE(cs.room,'') AS details,'' AS source,u.display_name AS actor,NULL AS points,0 AS reversible FROM class_sessions cs JOIN users u ON u.id=cs.opened_by WHERE cs.course_id=?`).bind(courseId),
    db.prepare(`SELECT cs.id||':closed' AS id,cs.closed_at AS time,'Session closed' AS eventType,'' AS studentId,'' AS name,cs.title AS session,COALESCE(cs.room,'') AS details,'' AS source,COALESCE((SELECT u.display_name FROM audit_log al JOIN users u ON u.id=al.actor_id WHERE al.entity_id=cs.id AND al.action='session.closed' ORDER BY al.created_at DESC LIMIT 1),'—') AS actor,NULL AS points,0 AS reversible FROM class_sessions cs WHERE cs.course_id=? AND cs.closed_at IS NOT NULL`).bind(courseId),
    db.prepare(`SELECT a.id,a.recorded_at AS time,'Attendance recorded' AS eventType,s.student_number AS studentId,s.name,cs.title AS session,a.source AS details,a.source,u.display_name AS actor,NULL AS points,0 AS reversible FROM attendance a JOIN students s ON s.id=a.student_id JOIN class_sessions cs ON cs.id=a.session_id JOIN users u ON u.id=a.recorded_by WHERE cs.course_id=?`).bind(courseId),
    db.prepare(`SELECT a.id||':voided' AS id,a.voided_at AS time,'Attendance corrected' AS eventType,s.student_number AS studentId,s.name,cs.title AS session,COALESCE(a.void_reason,'Teacher correction') AS details,'Teacher correction' AS source,COALESCE(u.display_name,'—') AS actor,NULL AS points,0 AS reversible FROM attendance a JOIN students s ON s.id=a.student_id JOIN class_sessions cs ON cs.id=a.session_id LEFT JOIN users u ON u.id=a.voided_by WHERE cs.course_id=? AND a.voided_at IS NOT NULL`).bind(courseId),
    db.prepare(`SELECT pt.id,pt.created_at AS time,CASE WHEN pt.reverses_transaction_id IS NOT NULL THEN 'Points reversed' WHEN COALESCE(pt.source,CASE WHEN pt.award_id IS NOT NULL THEN 'qr' WHEN pt.identity_verification='teacher_manual' THEN 'teacher_direct' ELSE 'qr' END)='teacher_direct' THEN 'Points awarded directly' ELSE 'Points earned' END AS eventType,s.student_number AS studentId,s.name,COALESCE(cs.title,'Independent coursework') AS session,pt.reason AS details,CASE COALESCE(pt.source,CASE WHEN pt.award_id IS NOT NULL THEN 'qr' WHEN pt.identity_verification='teacher_manual' THEN 'teacher_direct' ELSE 'qr' END) WHEN 'teacher_direct' THEN 'Teacher direct' WHEN 'teacher_correction' THEN 'Teacher correction' ELSE 'QR' END AS source,u.display_name AS actor,pt.points,CASE WHEN pt.points>0 AND pt.reverses_transaction_id IS NULL AND NOT EXISTS(SELECT 1 FROM point_transactions reversal WHERE reversal.reverses_transaction_id=pt.id) THEN 1 ELSE 0 END AS reversible FROM point_transactions pt JOIN students s ON s.id=pt.student_id JOIN users u ON u.id=pt.recorded_by LEFT JOIN point_awards pa ON pa.id=pt.award_id LEFT JOIN point_transactions original ON original.id=pt.reverses_transaction_id LEFT JOIN point_awards original_pa ON original_pa.id=original.award_id LEFT JOIN class_sessions cs ON cs.id=COALESCE(pa.session_id,original_pa.session_id,pt.manual_session_id,original.manual_session_id) WHERE pt.course_id=?`).bind(courseId),
    db.prepare(`SELECT pa.id||':created' AS id,pa.created_at AS time,'Points QR created' AS eventType,'' AS studentId,'' AS name,COALESCE(cs.title,'Independent coursework') AS session,pa.reason || CASE WHEN pa.restricted=1 THEN ' · Selected students (' || (SELECT COUNT(*) FROM point_award_recipients pr WHERE pr.award_id=pa.id) || ')' ELSE ' · All joined students' END || CASE WHEN pa.closed_at IS NOT NULL THEN ' · Deactivated' WHEN pa.expiry_mode='course' THEN ' · No time limit while course is active' WHEN pa.expiry_mode='session' THEN ' · Until class closes' ELSE ' · Expires ' || datetime(pa.expires_at,'unixepoch') || ' UTC' END AS details,'QR' AS source,u.display_name AS actor,pa.points,0 AS reversible,pa.id AS qrAwardId,CASE WHEN pa.closed_at IS NULL THEN 1 ELSE 0 END AS qrOpen FROM point_awards pa LEFT JOIN class_sessions cs ON cs.id=pa.session_id JOIN users u ON u.id=pa.awarded_by WHERE COALESCE(pa.course_id,cs.course_id)=?`).bind(courseId),
  ];
  const results=await Promise.all(queries.map(query=>query.all<EventRecord>()));
  return results.flatMap(result=>result.results).sort((a,b)=>b.time-a.time);
}

export async function loadCourseBackup(courseId:string){
  const db=env.DB,course=await db.prepare(`SELECT id,code,name,owner_id AS ownerId,created_at AS createdAt FROM courses WHERE id=?`).bind(courseId).first();
  const queries={scheduledClasses:`SELECT * FROM scheduled_classes WHERE course_id=?`,teachers:`SELECT ct.teacher_id AS teacherId,u.display_name AS name,u.email,ct.role,ct.joined_at AS joinedAt FROM course_teachers ct JOIN users u ON u.id=ct.teacher_id WHERE ct.course_id=?`,students:`SELECT s.id,s.student_number AS studentNumber,s.name,s.email,e.active,e.checked_in_at AS checkedInAt FROM enrolments e JOIN students s ON s.id=e.student_id WHERE e.course_id=?`,sessions:`SELECT id,title,room,opened_by AS openedBy,opened_at AS openedAt,closed_at AS closedAt FROM class_sessions WHERE course_id=?`,attendance:`SELECT a.* FROM attendance a JOIN class_sessions cs ON cs.id=a.session_id WHERE cs.course_id=?`,awards:`SELECT pa.* FROM point_awards pa LEFT JOIN class_sessions cs ON cs.id=pa.session_id WHERE COALESCE(pa.course_id,cs.course_id)=?`,awardRecipients:`SELECT pr.* FROM point_award_recipients pr JOIN point_awards pa ON pa.id=pr.award_id LEFT JOIN class_sessions cs ON cs.id=pa.session_id WHERE COALESCE(pa.course_id,cs.course_id)=?`,points:`SELECT * FROM point_transactions WHERE course_id=?`,nicknames:`SELECT * FROM leaderboard_preferences WHERE course_id=?`,audit:`SELECT * FROM audit_log WHERE course_id=?`};
  const result:Record<string,unknown>={exportedAt:new Date().toISOString(),course};
  for(const [key,sql] of Object.entries(queries))result[key]=(await db.prepare(sql).bind(courseId).all()).results;
  const nicknames=new Map((result.nicknames as {student_id:string;alias:string|null}[]).map(row=>[row.student_id,row.alias??'']));
  for(const key of ['students','attendance','points','awardRecipients']){
    result[key]=(result[key] as Record<string,unknown>[]).map(row=>({...row,nickname:nicknames.get(String(key==='students'?row.id:row.student_id))??''}));
  }
  return result;
}
