'use client';

import { FormEvent, useState, useTransition } from 'react';
import { choosePilotNickname, redeemPilot } from './actions';
import { redemptionFailure, redemptionLabels } from './redemption-errors';

type RedeemResult={ok:boolean;message:string;courseId?:string;nickname?:string|null;availableNicknames?:readonly string[]};

export default function PilotRedeem({ kind, token }: { kind:'attendance'|'points'|'onboarding'; token:string }) {
  const [studentNumber,setStudentNumber]=useState('');
  const [result,setResult]=useState<RedeemResult|null>(null);
  const [nickname,setNickname]=useState('');
  const [nicknameError,setNicknameError]=useState('');
  const [pending,startTransition]=useTransition();
  function submit(event:FormEvent){event.preventDefault();startTransition(async()=>{try{const next=await redeemPilot(kind,token,studentNumber) as RedeemResult;setResult(next);setNickname(next.availableNicknames?.[0]??'')}catch{setResult(redemptionFailure(kind,'CONNECTION','We could not confirm the result. Check your connection, refresh and try again. Repeating a scan will not award duplicate points.'))}})}
  function saveNickname(){if(!nickname)return;setNicknameError('');startTransition(async()=>{try{const saved=await choosePilotNickname(kind,token,studentNumber,nickname);if(!saved.ok){setNicknameError('message' in saved?saved.message:redemptionFailure(kind,'NICKNAME-RETRY','Could not save your nickname. Please try again.').message);return}setResult(current=>current?{...current,nickname:saved.nickname??nickname,courseId:saved.courseId}:current)}catch{setNicknameError(redemptionFailure(kind,'NICKNAME-CONNECTION','We could not confirm that your nickname was saved. Check your connection and try again.').message)}})}
  return <main className="redeem-page"><section className={`redeem-card ${result?(result.ok?'success':'failure'):''}`}><div className="brand"><b>P</b>Pulse</div><div className="pilot-badge">PUBLIC PILOT · IDENTITY NOT VERIFIED</div><p className="redemption-step">{redemptionLabels[kind]}</p>{result?<><i>{result.ok?'✓':'!'}</i><h1>{result.ok?(kind==='onboarding'?'Join your course':'All done'):`${redemptionLabels[kind]} could not be completed`}</h1><p role={result.ok?'status':'alert'}>{result.message}</p>{!result.ok&&<p className="redeem-help">Send your teacher this full message, including the reference in brackets.</p>}{result.ok&&(result.nickname?<div className="nickname-done"><small>YOUR COURSE NICKNAME</small><strong>{result.nickname}</strong><a href={`/league/${result.courseId}`}>View the course league →</a></div>:<div className="nickname-picker"><small>{kind==='onboarding'?'FINISH JOINING':'JOIN THE COURSE LEAGUE'}</small><h2>Choose your animal</h2><p>This nickname stays with you for every class in this course.</p><label className="field">Animal nickname<select value={nickname} onChange={e=>setNickname(e.target.value)}>{result.availableNicknames?.map(name=><option value={name} key={name}>{name}</option>)}</select></label>{nicknameError&&<p className="nickname-error">{nicknameError}</p>}<button className="dark create" disabled={pending||!nickname} onClick={saveNickname}>{pending?'Saving…':kind==='onboarding'?'Join course':'Claim this nickname'}</button></div>)}{!result.ok&&<button className="pilot-again" onClick={()=>setResult(null)}>Try again</button>}</>:<><h1>{kind==='onboarding'?'Join the course':kind==='attendance'?'Record attendance':'Claim participation points'}</h1><p>{kind==='onboarding'?'Join this course and choose your nickname. You can join before classes start; no open session is needed.':kind==='attendance'?'This QR records attendance for a class. To join the course first, ask for the Course onboarding QR.':'This QR claims participation points. You must have joined the course first.'}</p><form onSubmit={submit}><label className="field">Student number<input autoFocus autoComplete="off" value={studentNumber} onChange={e=>setStudentNumber(e.target.value)} placeholder="e.g. 12345 or fc12345" autoCapitalize="none" autoCorrect="off" required/></label><button className="dark create" disabled={pending}>{pending?'Checking…':kind==='onboarding'?'Continue':kind==='attendance'?'Record attendance':'Claim points'}</button></form></>}<footer>Pilot records are marked as unverified.</footer></section></main>;
}
