import { integer, sqliteTable, text, uniqueIndex, index, primaryKey } from 'drizzle-orm/sqlite-core';

export const courseOnboardingQrs = sqliteTable('course_onboarding_qrs', {
  courseId: text('course_id').primaryKey().references(() => courses.id, { onDelete: 'cascade' }),
  token: text('token').notNull(),
  tokenDigest: text('token_digest').notNull(),
}, t => [uniqueIndex('idx_course_onboarding_qrs_digest').on(t.tokenDigest)]);

export const users = sqliteTable('users', { id: text('id').primaryKey(), email: text('email').notNull(), displayName: text('display_name').notNull(), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, t => [uniqueIndex('idx_users_email').on(t.email)]);
export const courses = sqliteTable('courses', { id: text('id').primaryKey(), code: text('code').notNull(), name: text('name').notNull(), ownerId: text('owner_id').notNull().references(() => users.id), onboardingTokenDigest: text('onboarding_token_digest'), archivedAt: integer('archived_at', { mode: 'timestamp' }), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, t => [index('idx_courses_owner').on(t.ownerId), uniqueIndex('idx_courses_onboarding_token').on(t.onboardingTokenDigest)]);
export const courseTeachers = sqliteTable('course_teachers', { courseId: text('course_id').notNull().references(() => courses.id, { onDelete: 'cascade' }), teacherId: text('teacher_id').notNull().references(() => users.id), role: text('role', { enum: ['owner', 'editor'] }).notNull(), invitedBy: text('invited_by').notNull().references(() => users.id), joinedAt: integer('joined_at', { mode: 'timestamp' }).notNull() }, t => [uniqueIndex('idx_course_teacher_unique').on(t.courseId, t.teacherId)]);
export const students = sqliteTable('students', { id: text('id').primaryKey(), studentNumber: text('student_number').notNull(), name: text('name').notNull(), email: text('email'), userId: text('user_id').references(() => users.id) }, t => [uniqueIndex('idx_students_number').on(t.studentNumber), uniqueIndex('idx_students_user').on(t.userId)]);
export const enrolments = sqliteTable('enrolments', { courseId: text('course_id').notNull().references(() => courses.id, { onDelete: 'cascade' }), studentId: text('student_id').notNull().references(() => students.id), active: integer('active', { mode: 'boolean' }).notNull().default(true), groups: text('groups').notNull().default(''), checkedInAt: integer('checked_in_at', { mode: 'timestamp' }) }, t => [uniqueIndex('idx_enrolment_unique').on(t.courseId, t.studentId), index('idx_enrolments_checked_in').on(t.courseId,t.checkedInAt)]);
export const classSessions = sqliteTable('class_sessions', { id: text('id').primaryKey(), courseId: text('course_id').notNull().references(() => courses.id), title: text('title').notNull(), room: text('room'), attendanceTokenDigest: text('attendance_token_digest').notNull(), attendanceExpiresAt: integer('attendance_expires_at', { mode: 'timestamp' }).notNull(), openedBy: text('opened_by').notNull().references(() => users.id), openedAt: integer('opened_at', { mode: 'timestamp' }).notNull(), closedAt: integer('closed_at', { mode: 'timestamp' }) }, t => [index('idx_sessions_course_opened').on(t.courseId, t.openedAt), uniqueIndex('idx_sessions_attendance_token').on(t.attendanceTokenDigest)]);
export const attendance = sqliteTable('attendance', { id: text('id').primaryKey(), sessionId: text('session_id').notNull().references(() => classSessions.id), studentId: text('student_id').notNull().references(() => students.id), recordedBy: text('recorded_by').notNull().references(() => users.id), source: text('source', { enum: ['qr', 'manual', 'pilot'] }).notNull(), identityVerification: text('identity_verification', { enum: ['institutional', 'pilot_student_number'] }).notNull().default('institutional'), recordedAt: integer('recorded_at', { mode: 'timestamp' }).notNull() }, t => [uniqueIndex('idx_attendance_session_student').on(t.sessionId, t.studentId)]);
export const pointAwards = sqliteTable('point_awards', { id: text('id').primaryKey(), sessionId: text('session_id').references(() => classSessions.id), courseId: text('course_id').references(() => courses.id), expiryMode: text('expiry_mode', {enum:['timed','session','course']}).notNull().default('timed'), restricted: integer('restricted', {mode:'boolean'}).notNull().default(false), points: integer('points').notNull(), reason: text('reason').notNull(), tokenDigest: text('token_digest').notNull(), awardedBy: text('awarded_by').notNull().references(() => users.id), expiresAt: integer('expires_at', { mode: 'timestamp' }).notNull(), closedAt: integer('closed_at', { mode: 'timestamp' }), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, t => [uniqueIndex('idx_awards_token').on(t.tokenDigest), index('idx_awards_course_created').on(t.courseId,t.createdAt), index('idx_awards_session_created').on(t.sessionId, t.createdAt)]);
export const pointAwardRecipients = sqliteTable('point_award_recipients', { awardId: text('award_id').notNull().references(()=>pointAwards.id), studentId: text('student_id').notNull().references(()=>students.id) }, t=>[primaryKey({columns:[t.awardId,t.studentId]})]);
export const pointTransactions = sqliteTable('point_transactions', { id: text('id').primaryKey(), awardId: text('award_id').references(() => pointAwards.id), courseId: text('course_id').notNull().references(() => courses.id), studentId: text('student_id').notNull().references(() => students.id), points: integer('points').notNull(), reason: text('reason').notNull(), recordedBy: text('recorded_by').notNull().references(() => users.id), source: text('source', { enum: ['qr', 'teacher_direct', 'teacher_correction'] }), identityVerification: text('identity_verification', { enum: ['institutional', 'pilot_student_number'] }).notNull().default('institutional'), reversesTransactionId: text('reverses_transaction_id'), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, t => [uniqueIndex('idx_transaction_award_student').on(t.awardId, t.studentId), index('idx_transactions_course_student').on(t.courseId, t.studentId)]);
export const leaderboardPreferences = sqliteTable('leaderboard_preferences', { courseId: text('course_id').notNull().references(() => courses.id, { onDelete: 'cascade' }), studentId: text('student_id').notNull().references(() => students.id), visibility: text('visibility', { enum: ['private', 'student_number', 'alias'] }).notNull().default('private'), alias: text('alias') }, t => [uniqueIndex('idx_leaderboard_student').on(t.courseId, t.studentId), uniqueIndex('idx_leaderboard_alias').on(t.courseId, t.alias)]);
export const auditLog = sqliteTable('audit_log', { id: text('id').primaryKey(), courseId: text('course_id').notNull().references(() => courses.id), actorId: text('actor_id').notNull().references(() => users.id), action: text('action').notNull(), entityType: text('entity_type').notNull(), entityId: text('entity_id').notNull(), details: text('details'), createdAt: integer('created_at', { mode: 'timestamp' }).notNull() }, t => [index('idx_audit_course_created').on(t.courseId, t.createdAt)]);
export const pilotRateLimits = sqliteTable('pilot_rate_limits', { clientKey: text('client_key').primaryKey(), windowStartedAt: integer('window_started_at').notNull(), failedAttempts: integer('failed_attempts').notNull().default(0), blockedUntil: integer('blocked_until') });

export const scheduledClasses = sqliteTable('scheduled_classes', {
 id:text('id').primaryKey(),courseId:text('course_id').notNull().references(()=>courses.id),classId:text('class_id').notNull(),
 date:text('class_date').notNull(),week:integer('week').notNull(),time:text('class_time').notNull(),room:text('room').notNull(),teacher:text('teacher').notNull(),comments:text('comments').notNull().default(''),
 sessionId:text('session_id').references(()=>classSessions.id),importedBy:text('imported_by').notNull().references(()=>users.id),createdAt:integer('created_at').notNull()
},t=>[uniqueIndex('idx_scheduled_course_class').on(t.courseId,t.classId),index('idx_scheduled_course_date').on(t.courseId,t.date,t.time)]);
export const teacherAccounts = sqliteTable('teacher_accounts', {
 id:text('id').primaryKey(),email:text('email').notNull(),displayName:text('display_name').notNull(),
 role:text('role',{enum:['teacher','viewer']}).notNull(),codeDigest:text('code_digest').notNull(),
 disabledAt:integer('disabled_at'),sessionVersion:integer('session_version').notNull().default(1),
 createdBy:text('created_by').notNull(),createdAt:integer('created_at').notNull()
},t=>[uniqueIndex('idx_teacher_accounts_email').on(t.email),uniqueIndex('idx_teacher_accounts_code').on(t.codeDigest)]);
export const studentIdentityLinks = sqliteTable('student_identity_links', {
 provider:text('provider').notNull(),subject:text('subject').notNull(),studentId:text('student_id').notNull().references(()=>students.id),
 linkedBy:text('linked_by').notNull(),linkedAt:integer('linked_at').notNull()
},t=>[primaryKey({columns:[t.provider,t.subject]}),uniqueIndex('idx_identity_provider_student').on(t.provider,t.studentId)]);
