// Synthetic integration checks: credentials, session revocation and every write action.
const fs=require('node:fs');
let source=fs.readFileSync('qa/point-awards.test.cjs','utf8');
source=source.slice(0,source.lastIndexOf('main().catch'));
source+=String.raw`
async function teacherChecks(){
 sqlite.exec(fs.readFileSync('drizzle/0011_teacher_accounts.sql','utf8'));
 process.env.PILOT_TEACHERS_JSON=JSON.stringify([{id:'teacher',displayName:'Teacher',email:'teacher@example.test',code:'synthetic-admin-code'},{id:'second',displayName:'Second',email:'second@example.test',code:'synthetic-second-code'}]);
 process.env.PILOT_TEACHER_SECRET='synthetic-local-test-secret-not-a-real-credential';
 const jar=new Map(),cookieApi={get:key=>jar.has(key)?{value:jar.get(key)}:undefined,set:(key,value)=>jar.set(key,value),delete:key=>jar.delete(key)};
 const store=load('app/teacher-store.ts',{'cloudflare:workers':{env:{DB:db}}});
 const auth=load('app/pilot-auth.ts',{'cloudflare:workers':{env:{DB:db}},'next/headers':{cookies:async()=>cookieApi},'./teacher-store':store,'./request-security':security});
 const identities=load('app/student-identity-actions.ts',{'cloudflare:workers':{env:{DB:db}},'next/cache':{revalidatePath(){}},'./pilot-auth':auth});
 const management=load('app/teacher-actions.ts',{'cloudflare:workers':{env:{DB:db}},'next/cache':{revalidatePath(){}},'./pilot-auth':auth,'./teacher-store':store});
 await assert.rejects(()=>auth.getPilotTeacherDirectory(),/Sign in/);
 await assert.rejects(()=>management.getTeacherAccounts(),/administrator/);
 assert.equal((await auth.pilotLogin('synthetic-admin-code')).ok,true);
 assert.equal((await auth.getPilotTeacherSession()).role,'admin');
 await assert.rejects(()=>identities.linkStudentIdentity({studentNumber:'fc1',subject:'verified-reference',verified:false}),/Confirm/);
 await identities.linkStudentIdentity({studentNumber:'fc1',subject:'verified-reference',verified:true});
 await identities.linkStudentIdentity({studentNumber:'FC1',subject:'verified-reference',verified:true});
 await assert.rejects(()=>identities.linkStudentIdentity({studentNumber:'fc2',subject:'verified-reference',verified:true}),/another link/);
 await identities.correctStudentIdentity({studentNumber:'fc4',name:'Verified Student Four',email:'verified-four@example.test',verified:true});
 assert.equal(sqlite.prepare("SELECT name FROM students WHERE id='s4'").get().name,'Verified Student Four');
 assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM audit_log WHERE action='student.identity_corrected' AND course_id='other'").get().n,1);
 const created=await management.addTeacherAccount({displayName:'Test Teacher',email:'test-teacher@pulse.invalid',readOnly:true,courseIds:[]});
 const viewer=sqlite.prepare("SELECT * FROM teacher_accounts WHERE role='viewer'").get();
 assert.notEqual(viewer.code_digest,created.code);
 const teacher=await management.addTeacherAccount({displayName:'New Teacher',email:'new@example.test',readOnly:false,courseIds:['course']});
 assert.equal(sqlite.prepare("SELECT COUNT(*) n FROM course_teachers ct JOIN teacher_accounts ta ON ta.id=ct.teacher_id WHERE ta.email='new@example.test' AND ct.course_id='course' AND ct.role='editor'").get().n,1);
 await assert.rejects(()=>management.addTeacherAccount({displayName:'Duplicate',email:'new@example.test',readOnly:false,courseIds:[]}));
 await assert.rejects(()=>management.addTeacherAccount({displayName:'Out of scope',email:'other@example.test',readOnly:false,courseIds:['other']}),/own/);
 await auth.pilotLogin(created.code);
 assert.equal((await auth.getPilotTeacherSession()).role,'viewer');
 await assert.rejects(()=>identities.linkStudentIdentity({studentNumber:'fc2',subject:'bad-reference',verified:true}),/administrator/);
 await assert.rejects(()=>identities.correctStudentIdentity({studentNumber:'fc2',name:'Bad',email:'bad@example.test',verified:true}),/administrator/);
 assert.equal('code' in await auth.getPilotTeacherSession(),false);
 await assert.rejects(()=>management.addTeacherAccount({displayName:'Escalation',email:'bad@example.test',readOnly:false,courseIds:[]}),/administrator/);
 await assert.rejects(()=>management.resetTeacherCode(viewer.id),/administrator/);
 await assert.rejects(()=>management.setTeacherAccountEnabled(viewer.id,false),/administrator/);
 const oldSession=jar.get('pulse_pilot_teacher');
 await auth.pilotLogin('synthetic-admin-code');
 const reset=await management.resetTeacherCode(viewer.id);
 jar.set('pulse_pilot_teacher',oldSession);assert.equal(await auth.getPilotTeacherSession(),null);
 assert.equal((await auth.pilotLogin(created.code)).ok,false);
 assert.equal((await auth.pilotLogin(reset.code)).ok,true);
 const newSession=jar.get('pulse_pilot_teacher');
 await auth.pilotLogin('synthetic-admin-code');await management.setTeacherAccountEnabled(viewer.id,false);
 jar.set('pulse_pilot_teacher',newSession);assert.equal(await auth.getPilotTeacherSession(),null);
 assert.equal((await auth.pilotLogin(reset.code)).ok,false);
 await auth.pilotLogin('synthetic-admin-code');await management.setTeacherAccountEnabled(viewer.id,true);
 assert.equal((await auth.pilotLogin(reset.code)).ok,true);
 jar.set('pulse_pilot_teacher',newSession);assert.equal(await auth.getPilotTeacherSession(),null);
 await auth.pilotLogin(reset.code);
 const directory=await auth.getPilotTeacherDirectory();assert.ok(directory.some(t=>t.email==='new@example.test'));assert.ok(directory.every(t=>t.role!=='viewer'&&!('code' in t)&&!('code_digest' in t)));
 await auth.pilotLogin(teacher.code);await assert.rejects(()=>management.getTeacherAccounts(),/administrator/);
 await auth.pilotLogin(reset.code);
 user={userId:viewer.id,email:viewer.email,displayName:'Test Teacher',readOnly:true,teacherAccess:true};
 const before=snapshot();
 const reads=load('app/data.ts',{'cloudflare:workers':{env:{DB:db}},'next/headers':{cookies:async()=>cookieApi},'./pilot-auth':auth});
 assert.equal((await reads.ensureTeacher(user)).id,'course');
 const dashboard=await reads.getDashboard(user);assert.equal(dashboard.readOnly,true);assert.equal(dashboard.courses.length,2);
 await actions.getCourseRecords();await actions.getLiveClassroom('session');await actions.getScheduledClasses('course');await actions.switchCourse('other');
 const exporter=load('app/export/[courseId]/[kind]/route.ts',{'cloudflare:workers':{env:{DB:db}},'../../../chatgpt-auth':{getChatGPTUser:async()=>user},'../../../course-records':records});
 assert.equal((await exporter.GET(new Request('http://local'),{params:Promise.resolve({courseId:'other',kind:'enrolments'})})).status,200);
 const mutations=[()=>actions.createCourse({code:'BAD',name:'Bad course',teacherIds:[]}),()=>actions.importTimetable('course',[]),()=>actions.startScheduledClass('course','schedule',30),()=>actions.importClassAttendance('course','schedule',[{classId:'T01',studentNumber:'fc1'}],randomUUID()),()=>actions.importRoster('course','courseid_TEST_participants.csv',[]),()=>actions.openSession({title:'bad',room:'',attendanceMinutes:30}),()=>actions.closeSession('session'),()=>actions.rotateAttendanceToken('session'),()=>actions.generateOnboardingQr(),()=>actions.createAward(input),()=>actions.closePointAward('legacy'),()=>actions.addManualRecord({kind:'points',sessionId:'session',studentNumber:'fc1',points:5,reason:'bad'}),()=>actions.voidAttendance('absent','bad'),()=>actions.reversePointTransaction('legacy-claim','bad')];
 for(const mutate of mutations)await assert.rejects(mutate);
 assert.equal((await actions.redeem('attendance','attendance')).ok,false);
 assert.equal((await actions.redeemPilot('onboarding','anything','fc1')).ok,false);
 assert.equal((await actions.choosePilotNickname('onboarding','anything','fc1','Owl')).ok,false);
 assert.equal(snapshot(),before,'Read-only requests must not change any database table');
 console.log('PASS: teacher creation, course assignment, protected directory, role separation, credential reset/revocation, read-only browsing/exports, and all 16 mutation paths blocked with zero database changes.');
}
function snapshot(){return JSON.stringify(sqlite.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all().map(({name})=>[name,sqlite.prepare('SELECT * FROM '+name+' ORDER BY rowid').all()]));}
teacherChecks().catch(e=>{console.error(e);process.exitCode=1});
`;
new Function('require',source)(require);
