import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import XLSX from 'xlsx';
import {DatabaseSync} from 'node:sqlite';
const js=ts.transpileModule(fs.readFileSync('app/roster-import.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {parseRoster,validateRoster,rosterCourseCode}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const filename='courseid_EN2026_participants.csv',rosterPath='local-data/rosters/'+filename,wb=XLSX.read(fs.readFileSync(rosterPath,'utf8'),{type:'string',raw:true});
const grid=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,raw:true,defval:''});
const preview=parseRoster(grid,filename,'EN2026');
assert.equal(preview.length,152);assert.equal(preview.filter(r=>r.status==='error').length,2);
const rows=preview.filter(r=>r.status!=='error');
assert.equal(rows.filter(r=>r.status==='error').length,0);
assert.equal(validateRoster(rows).length,rows.length);
assert.throws(()=>parseRoster(grid,filename,'BIO204'),/Select that course/);
assert.throws(()=>rosterCourseCode('Students.csv'));
assert.throws(()=>parseRoster([['First name']],filename,'EN2026'));
const sample=[grid[0],['José','Ávila','000123','test@example.org','TP1, TP2']];
const parsed=parseRoster(sample,filename,'EN2026');
assert.equal(parsed[0].studentId,'000123');assert.equal(parsed[0].name,'José Ávila');assert.equal(parsed[0].groups,'TP1, TP2');
assert.equal(parseRoster([...sample,sample[1]],filename,'EN2026')[1].status,'error');
assert.throws(()=>validateRoster([parsed[0],parsed[0]]),/Duplicate/);
assert.equal(parseRoster(sample,filename,'EN2026',['000123'])[0].status,'update');
const db=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+file,'utf8'));
db.exec("INSERT INTO users VALUES ('teacher','teacher@example.org','Teacher',0); INSERT INTO courses (id,code,name,owner_id,created_at) VALUES ('course','EN2026','Course','teacher',0)");
const source=fs.readFileSync('app/actions.ts','utf8');
const insertStudent=source.match(/db\.prepare\(`(INSERT INTO students \(id,student_number,name,email\)[\s\S]*?)`\)/)[1];
const insertEnrolment=source.match(/db\.prepare\(`(INSERT INTO enrolments \(course_id,student_id,active,groups\)[\s\S]*?)`\)/)[1];
function save(){db.exec('BEGIN');try{for(const [i,row] of rows.entries()){db.prepare(insertStudent).run('s'+i,row.studentId,row.name,row.email);db.prepare(insertEnrolment).run('course',row.groups,row.studentId)}db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
save();save();
assert.equal(db.prepare('SELECT COUNT(*) n FROM enrolments').get().n,rows.length);
assert.equal(db.prepare('SELECT COUNT(*) n FROM students').get().n,rows.length);
assert.equal(db.prepare('SELECT COUNT(*) n FROM enrolments WHERE checked_in_at IS NOT NULL').get().n,0);
db.exec("INSERT INTO courses (id,code,name,owner_id,created_at) VALUES ('other','OTHER','Other course','teacher',0); INSERT INTO students (id,student_number,name) VALUES ('old','old-id','Old student'); INSERT INTO enrolments (course_id,student_id,active,checked_in_at) VALUES ('course','old',1,1),('other','old',1,1)");
const reset=source.match(/db\.prepare\('(UPDATE enrolments SET active=0,checked_in_at=NULL WHERE course_id=\?)'\)/)[1];
db.exec('BEGIN');db.prepare(reset).run('course');
for(const row of rows)db.prepare(insertEnrolment).run('course',row.groups,row.studentId);
db.exec('COMMIT');
assert.equal(db.prepare("SELECT COUNT(*) n FROM enrolments WHERE course_id='course' AND active=1").get().n,150);
assert.equal(db.prepare("SELECT active FROM enrolments WHERE course_id='course' AND student_id='old'").get().active,0);
assert.equal(db.prepare("SELECT checked_in_at FROM enrolments WHERE course_id='other' AND student_id='old'").get().checked_in_at,1);
assert.equal(db.prepare("SELECT COUNT(*) n FROM enrolments WHERE course_id='course' AND checked_in_at IS NOT NULL").get().n,0);
db.exec('BEGIN');db.prepare(reset).run('course');db.exec('ROLLBACK');
assert.equal(db.prepare("SELECT COUNT(*) n FROM enrolments WHERE course_id='course' AND active=1").get().n,150);
console.log(JSON.stringify({participants:rows.length,errors:0,migration:'passed',repeatImport:'no duplicates',leadingZeros:'preserved',groups:'preserved',wrongCourse:'blocked'}));
console.log('Replacement: 150 active; old enrolment inactive; other course unchanged; rollback preserves roster.');
